[metadata]
name = djapian
version = 0.1
description = Djapian index search
long_description = file: README.rst
url = https://masterme.ru
author = Denis Yaroslavtsev
author_email = admin@masterme.ru
license = MIT
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 4.3
    Intended Audience :: Developers
    License :: OSI Approved :: MIT
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find:
python_requires = >=3.6
install_requires =
    django >= 4.3
    hunspell == 0.5.5
    #xapian-bindings == 0.1.0 # пока отключил (недоступно постоянно oligarchy.co.uk), лучше собирать из xapian-bindings-1.4.29.tar.xz

[options.packages.find]
exclude =
    *__pycache__*
