# Generated by Django 3.2 on 2023-12-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
