# Generated by Django 2.2.3 on 2024-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapian', '0002_alter_change_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
