# Generated by Django 3.2.25 on 2024-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapian', '0003_auto_20240220_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
